# HIT Data science course - exercies 1 + 2

## Setup
Before the course begins, please install **one** of the following environments for writing and running Python code:

### Option 1 – Anaconda
* Anaconda is a platform for working with Python in data science.
* It comes with useful tools like Jupyter Notebook and common data science libraries.
* It helps manage packages and environments for different projects.
#### Please install Anaconda at https://www.anaconda.com/download

### Option 2 – Visual Studio Code
* Visual Studio Code (VS Code) is a code editor developed by Microsoft.
* It helps developers write, organize, run, and debug programs in many programming languages, including Python.
* It also supports extensions that add features such as Jupyter notebooks, Git integration, etc...
#### Please install Visual Studio Code at https://code.visualstudio.com/download?_exp_download=fb315fc982

### Kaggle
* Kaggle is a website where people can learn and practice data science using real datasets. https://www.kaggle.com/
* It has a "Learn" section with lessons and exercises. https://www.kaggle.com/learn
* It has a "Competitions" section where members can participate in data science competitions to practice and improve their skills. https://www.kaggle.com/competitions

#### Please create a Kaggle account, as we will use datasets from Kaggle during the course.
* Downloud "Diamonds.csv" dataset from Kaggle and save it in the "data" folder.

## Getting started- Data science tools and packages

### Pandas
* pandas is a Python library for working with structured data.
* It helps us load, clean, organize, analyze, and save data.
* It is especially useful for data in table format, like Excel files, CSV files, or database tables.
* The main object in pandas is called a DataFrame, which is similar to a table with rows and columns.

In [2]:
import pandas as pd

#### Read Data

* The main object in pandas is called a DataFrame, which is similar to a table with rows and columns.

The following cell of code loads data from a CSV file into a Pandas DataFrame.

note:
* pd.read_csv(...) reads a CSV file using the Pandas library.
* 'data/diamonds.csv' is the location of the file (change it to the location of your CSV file)
* sep=',' tells Pandas that the values in the file are separated by commas.
* index_col=0 tells Pandas to use the first column in the CSV file as the row index instead of treating it as a regular data column.
* diamonds_df = saves the loaded table in a variable called diamonds_df.

After running it, diamonds_df contains the diamonds dataset and can be used for data analysis.

In [29]:
diamonds_df = pd.read_csv('data/diamonds.csv', sep=',' , index_col=0)

* In The following cell, The head() method displays the first rows of a DataFrame.
* Recall that diamonds_df is the DataFrame that contains the diamonds dataset.
* .head(10) tells Pandas to display the first 10 rows of the DataFrame (chane it to display more or fewer rows using a different number).
* This method is commonly used to quickly inspect the data after loading it and verify that it looks correct.

In [30]:
diamonds_df.head(10)

    carat        cut color clarity  depth  table  price     x     y     z
1    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

#### OOP

In Object-Oriented Programming (OOP), an attribute is data that belongs to an object, while a method is an action/function that the object can perform.
* An attribute stores information about the object.
* A method is a function inside a class. It usually does something, often using or changing the object’s attributes.
* we access an attribute without parentheses, and a method with parentheses
* in the following 2 cells columns is an attribute (holds the column names of diamonds_df) example and info() is a method example (returns information about the diamonds_df):

In [31]:
diamonds_df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [32]:
diamonds_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 1 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.1 MB

note: float64 and int64 are both numeric data types, but they store different kinds of numbers
* int64 stores whole numbers only - integers.
* float64 stores decimal numbers.
* str (string) is the pandas type for text columns.

### Descriptive statistics

The describe() method generates a statistical summary (Descriptive statistics) of the numeric columns in a DataFrame.

For each numeric column, it displays:

* count – The number of non-missing (NaN) values.
* mean – The average value.
* std – The standard deviation, which measures how spread out the values are.
* min – The smallest value.
* 25% – The first quartile (25% of the values are below this number).
* 50% – The median (the middle value).
* 75% – The third quartile (75% of the values are below this number).
*  max – The largest value.

In [16]:
diamonds_df.describe().round()

         carat    depth    table    price        x        y        z
count  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0
mean       1.0     62.0     57.0   3933.0      6.0      6.0      4.0
std        0.0      1.0      2.0   3989.0      1.0      1.0      1.0
min        0.0     43.0     43.0    326.0      0.0      0.0      0.0
25%        0.0     61.0     56.0    950.0      5.0      5.0      3.0
50%        1.0     62.0     57.0   2401.0      6.0      6.0      4.0
75%        1.0     62.0     59.0   5324.0      7.0      7.0      4.0
max        5.0     79.0     95.0  18823.0     11.0     59.0     32.0

Use include=['str'] to describe string variables instead numeric

In [18]:
diamonds_df.describe(include=['str'])

          cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

To show only one chosen column out of diamonds_df use the name of it inside square brackets:

In [34]:
diamonds_df ["color"]

1        E
2        E
3        E
4        I
5        J
        ..
53936    D
53937    D
53938    D
53939    H
53940    D
Name: color, Length: 53940, dtype: str

In [35]:
diamonds_df["cut"]

1            Ideal
2          Premium
3             Good
4          Premium
5             Good
           ...
53936        Ideal
53937         Good
53938    Very Good
53939      Premium
53940        Ideal
Name: cut, Length: 53940, dtype: str

Use unique method to show the unique() possible values in a chosen column, or nunique() to count them

In [28]:
diamonds_df["color"].unique()

<StringArray>
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Length: 7, dtype: str